# CI pipeline for branches outside of 'master'
# Checks for successful builds
# TODO: Integrate with testing
name: CI Maven Pipeline

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file telegramresponsebotjava/pom.xml
# May want later? Artifact per build
#      - name: Upload artifact
#        uses: actions/upload-artifact@v2.2.4
#        with:
#          name: telegram-response-bot-java-build.jar
#          path: ./telegramresponsebotjava/target/telegram-response-bot-java-build.jar