on:
  workflow_run:
    workflows: ["CI"]
    branches: ["master"]
    types:
      - completed
      - requested

name: Create Release

jobs:
  on-success:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: telegram-response-bot-java-build.jar
          path: ./telegramresponsebotjava/target/telegram-response-bot-java-build.jar
          run: ls -R
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./telegramresponsebotjava/target/telegram-response-bot-java-build.jar
          asset_name: telegram-response-bot-java-build.jar
          asset_content_type: application/java-archive
